name: Docker Build and Publish

on:
  push:
    tags:
      - "*"

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Get tag name
        uses: actions/github-script@v4
        id: get_tag_name
        with:
          script: |
            const tag = context.payload.ref.replace('refs/tags/', '');
            return { tag: tag };
        
      - name: somethin
        run: |
          echo "Get tag name  ${{ steps.get_tag_name.outputs.tag }}"
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV
          echo "env.GIT_TAG  ${{ env.GIT_TAG }}"
          echo "GIT_TAG  ${{ GIT_TAG }}"
          
      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/go-swagger3:latest
            ${{ env.DOCKER_USERNAME }}/go-swagger3:${{ env.GIT_TAG }}
