name: Docker Build and Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/go-swagger3:latest
            ${{ env.DOCKER_USERNAME }}/go-swagger3:${{ github.sha }}

      - name: Get Docker Image Digest
        id: docker_digest
        run: echo "::set-output name=digest::$(docker inspect --format='{{index .RepoDigests 0}}' '${{ env.DOCKER_USERNAME }}/go-swagger3:${{ github.sha }}')"

      - name: Display Image Digest
        run: echo ${{ steps.docker_digest.outputs.digest }}
